/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;



/**
 *
 * @author 201912030004
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        setTitle("Arquivo de relatórios");
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        itemConsultarLancamentos = new javax.swing.JMenuItem();
        itemLancamento = new javax.swing.JMenuItem();
        painelDesktop = new javax.swing.JPanel();
        barramenu = new javax.swing.JMenuBar();
        menuAdicionar = new javax.swing.JMenu();
        itemFoguete = new javax.swing.JMenuItem();
        menuConsultar = new javax.swing.JMenu();
        itemConsultarFoguetes = new javax.swing.JMenuItem();

        itemConsultarLancamentos.setText("Lançamentos");

        itemLancamento.setText("Lançamento");
        itemLancamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemLancamentoActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        javax.swing.GroupLayout painelDesktopLayout = new javax.swing.GroupLayout(painelDesktop);
        painelDesktop.setLayout(painelDesktopLayout);
        painelDesktopLayout.setHorizontalGroup(
            painelDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 887, Short.MAX_VALUE)
        );
        painelDesktopLayout.setVerticalGroup(
            painelDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 503, Short.MAX_VALUE)
        );

        menuAdicionar.setText("Adicionar");

        itemFoguete.setText("Foguete");
        itemFoguete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemFogueteActionPerformed(evt);
            }
        });
        menuAdicionar.add(itemFoguete);

        barramenu.add(menuAdicionar);

        menuConsultar.setText("Acessar");

        itemConsultarFoguetes.setText("Foguetes");
        itemConsultarFoguetes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemConsultarFoguetesActionPerformed(evt);
            }
        });
        menuConsultar.add(itemConsultarFoguetes);

        barramenu.add(menuConsultar);

        setJMenuBar(barramenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelDesktop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelDesktop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        JanelaLogin janelaLogin = new JanelaLogin();
        painelDesktop.add(janelaLogin);
        janelaLogin.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void itemFogueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemFogueteActionPerformed
        JanelaAdicionarFoguete jaf = new JanelaAdicionarFoguete();
        painelDesktop.add(jaf);
        jaf.setVisible(true);
    }//GEN-LAST:event_itemFogueteActionPerformed

    private void itemLancamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemLancamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemLancamentoActionPerformed

    private void itemConsultarFoguetesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemConsultarFoguetesActionPerformed
        JanelaAcessarFoguetes jafo = new JanelaAcessarFoguetes();
        painelDesktop.add(jafo);
        jafo.setVisible(true);
    }//GEN-LAST:event_itemConsultarFoguetesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barramenu;
    private javax.swing.JMenuItem itemConsultarFoguetes;
    private javax.swing.JMenuItem itemConsultarLancamentos;
    private javax.swing.JMenuItem itemFoguete;
    private javax.swing.JMenuItem itemLancamento;
    private javax.swing.JMenu menuAdicionar;
    private javax.swing.JMenu menuConsultar;
    private javax.swing.JPanel painelDesktop;
    // End of variables declaration//GEN-END:variables
}
